org: thaer899
app: myresume-utils
service: myresume-utils
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: eu-west-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: main.app

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"
